apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: develop
  labels:
    app.kubernetes.io/component: keycloak
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      protocol: TCP
  selector:
    app: keycloak
