kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: keycloak
  namespace: develop
  labels:
    app.kubernetes.io/component: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  replicas: 1
  serviceName: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: bitnami/keycloak:21.1.2-debian-11-r5
        imagePullPolicy: IfNotPresent
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secrets
              key: admin-password
        - name: KEYCLOAK_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secrets
              key: db-password
        - name: KEYCLOAK_HTTP_RELATIVE_PATH
          value: "/"
        envFrom:
        - configMapRef:
            name: keycloak-config
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: infinispan
          containerPort: 7800
          protocol: TCP
        startupProbe:
          httpGet:
            path: "/"
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 60
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: "/"
            port: http
          initialDelaySeconds: 300
          periodSeconds: 1
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: "/realms/master"
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
      #  volumeMounts:
      #    - name: keycloak-config
      #      mountPath: /bitnami/keycloak/conf/keycloak.conf
      #volumes:
      #  - name: keycloak-config
      #    configMap:
      #      name: keycloak-properties
