apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:sts::889358452175:assumed-role/AdminRole/i-0311a62a770c0c630
      username: system:node:
      groups:
        - system:bootstrappers
        - system:nodes
