# An example of ClusterConfig object using an existing VPC:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: supreme-shop
  region: ap-south-1
  version: "1.27"

vpc:
  id: "vpc-029adcacc19142583"  # (optional, must match VPC ID used for each subnet below)
  cidr: "172.16.0.0/16"       # (optional, must match CIDR used by the given VPC)
  subnets:
    # must provide 'private' and/or 'public' subnets by availability zone as shown
    public:
      ap-south-1a:
        id: "subnet-0d87029a87deb446e"
        cidr: "172.16.128.0/18" # (optional, must match CIDR used by the given subnet)

      ap-south-1c:
        id: "subnet-08d901281e20269a7"
        cidr: "172.16.224.0/19"  # (optional, must match CIDR used by the given subnet)

      ap-south-1b:
        id: "subnet-07a8808f31307d05e"
        cidr: "172.16.192.0/19"   # (optional, must match CIDR used by the given subnet)

nodeGroups:
    - name: ng-1
      minSize: 2
      maxSize: 5
      instancesDistribution:
        maxPrice: 0.017
        instanceTypes: ["t3.small"] # At least one instance type should be specified
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
        spotInstancePools: 2
addons:
- name: vpc-cni # no version is specified so it deploys the default version
  attachPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
- name: coredns
  version: latest # auto discovers the latest available
- name: kube-proxy
  version: latest

iam:
  withOIDC: true

iamIdentityMappings:
  - arn: arn:aws:iam::889358452175:user/rpradhan
    groups:
      - system:masters
    username: rpradhan
    noDuplicateARNs: true
