apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    #service.beta.kubernetes.io/aws-load-balancer-internal: internet-facing
      #service.beta.kubernetes.io/aws-load-balancer-extra-security-groups: sg-041c51d486bcb3d58
      #service.beta.kubernetes.io/aws-load-balancer-type: external
      #service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
