kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: kafka
  namespace: develop
  labels:
    app.kubernetes.io/component: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  serviceName: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers: 
      - name: kafka
        image: bitnami/kafka:3.5.0-debian-11-r7
        imagePullPolicy: IfNotPresent
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_ENABLE_KRAFT
          value: "no"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092,EXTERNAL://:9094"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092"
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_ZOOKEEPER_PROTOCOL
          value: "PLAINTEXT"
        - name: KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES
          value: "1200000000"
        - name: KAFKA_VOLUME_DIR
          value: "/bitnami/kafka"
        ports:
        - name: client
          containerPort: 9092
        - name: internal
          containerPort: 9094
        - name: external
          containerPort: 9095
        volumeMounts:
          #- name: scripts
          #  mountPath: /scripts/setup.sh
          #  subPath: setup.sh
          - name: data
            mountPath: /bitnami/kafka
          - name: logs
            mountPath: /opt/bitnami/kafka/logs
          - name: shared
            mountPath: /shared
      volumes:
        #- name: scripts
        #  configMap:
        #    name: kafka-script
        #    defaultMode: 0755
        - name: data
          emptyDir: {}
        - name: logs
          emptyDir: {}
        - name: shared
          emptyDir: {}
