apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: develop
  labels:
    app.kubernetes.io/component: kafka
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 9092
      protocol: TCP
      targetPort: client
    - name: internal
      port: 9094
      protocol: TCP
      targetPort: internal
  selector:
    app: kafka
