apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: develop
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
  labels:
    app.kubernetes.io/component: kafka
spec:
  type: LoadBalancer
  ports:
    - name: external
      port: 9092
      protocol: TCP
  selector:
    app: kafka
