apiVersion: v1
kind: Service
metadata:
  name: axon-service
  namespace: develop
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  selector:
      app: axon
  type: LoadBalancer
  ports:
  - name: axon
    protocol: TCP
    port: 8024
---
apiVersion: v1
kind: Service
metadata:
  name: axon-grpc-service
  namespace: develop
spec:
  selector:
      app: axon
  type: ClusterIP
  ports:
  - name: axon
    protocol: TCP
    port: 8124
